In [4]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print('1D array:\n ',arr1)

arr2 = np.array([[1,2,3],[4,5,6]])
print('2D array:\n ',arr2)

arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Mul Dim array:\n ",arr3)

1D array:
  [1 2 3 4 5]
2D array:
  [[1 2 3]
 [4 5 6]]
Mul Dim array:
  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
identity = np.eye(10)
print(identity)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [11]:
full_array = np.full((10,5),'unbooked')
print(full_array)

[['unbooked' 'unbooked' 'unbooked' 'unbooked' 'unbooked']
 ['unbooked' 'unbooked' 'unbooked' 'unbooked' 'unbooked']
 ['unbooked' 'unbooked' 'unbooked' 'unbooked' 'unbooked']
 ['unbooked' 'unbooked' 'unbooked' 'unbooked' 'unbooked']
 ['unbooked' 'unbooked' 'unbooked' 'unbooked' 'unbooked']
 ['unbooked' 'unbooked' 'unbooked' 'unbooked' 'unbooked']
 ['unbooked' 'unbooked' 'unbooked' 'unbooked' 'unbooked']
 ['unbooked' 'unbooked' 'unbooked' 'unbooked' 'unbooked']
 ['unbooked' 'unbooked' 'unbooked' 'unbooked' 'unbooked']
 ['unbooked' 'unbooked' 'unbooked' 'unbooked' 'unbooked']]


In [15]:
range_arr = np.arange(1,40,2)
print(range_arr)
range_arr1 = np.arange(2,41,2)
print(range_arr1)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [20]:
lin_space = np.linspace(0,100,5)
'''
first 100/2   0 50 100
second        0 25 50 75 100
'''
print(lin_space)

[  0.  25.  50.  75. 100.]


In [32]:
rand_int = np.random.randint(1,20,(10,10))    # start,end,array size(row,cols)
print(rand_int)

[[14  6 13 10 16 16 16 15  6 12]
 [11 13 13 15  5  4 19 13  3 17]
 [ 8 16  9  6 12 10 15 12 17 10]
 [16  5 15 11  7  3  4 16 10 11]
 [16 18 19 13 11 19  4 11  5 18]
 [ 2 10  9  4 15 10  8  3 14 19]
 [14  8 13 17 11 17 16 11  6 17]
 [10 18 19  4  9 16 18 10  7  9]
 [13  8  3 18 18 19 19  6  5  6]
 [ 2 16 19 10 18  9 12 19 15  2]]


In [30]:
rand_int = np.random.randint(1,20)    # start,end gives single element
print(rand_int)

6


In [40]:
rand_int = np.random.rand(8,4)    # generates 0-1 and (rand(rows,cols))
print(rand_int)

[[0.8484102  0.26866815 0.40831844 0.80334756]
 [0.70082065 0.96047211 0.22772414 0.27945216]
 [0.03235253 0.22353977 0.9116036  0.94604862]
 [0.87990027 0.64337942 0.45590838 0.54449889]
 [0.196229   0.02197911 0.82486888 0.68937402]
 [0.310109   0.45751438 0.78038228 0.57405723]
 [0.52316161 0.77648418 0.43538709 0.59265604]
 [0.96031575 0.44716387 0.36349398 0.24454363]]


In [48]:
normal_distribution = np.random.randn(3,3)
print(normal_distribution)

[[ 0.16619458  0.35153649 -1.04404964]
 [ 0.40364894 -0.88213655 -0.0697343 ]
 [-0.36998251 -0.19214486 -0.76130097]]


In [52]:
rand_choice = np.random.choice(['html','css','python','jave','cpp'],2)    # (list, range)
print(rand_choice)

['cpp' 'jave']


In [67]:
np.random.seed(10)

rand_arr = np.random.randint(6)
print(rand_arr)

1


In [68]:
arr = np.array([[1,2],[5,4],[8,9],[7,4],[2,8],[5,2]])
print(arr.shape)

(6, 2)


In [73]:
reshape = arr.reshape(4,3)
print(reshape)

[[1 2 5]
 [4 8 9]
 [7 4 2]
 [8 5 2]]


In [79]:
a = np.array([[1,2,3,4],[5,6,7,3]])
flattened = a.flatten()
print(flattened)

[1 2 3 4 5 6 7 3]


In [80]:
transpose = a.T
print(transpose)

[[1 5]
 [2 6]
 [3 7]
 [4 3]]


In [87]:
arr = np.array([10,20,30,40,50,60])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[0:])
print(arr[::-1])
print(arr[:3])

10
60
[20 30 40]
[10 20 30 40 50 60]
[60 50 40 30 20 10]
[10 20 30]


In [88]:
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix[1,0])      # to access single element
print(matrix[0:3,1])    # to access same column values in range of rows
print(matrix[1:3,0:2])  # to access range of elements for rows and columns



40
[20 50 80]
[[40 50]
 [70 80]]


In [90]:
arr = np.array([2,4,6,8,10,12])
print(arr + 3)
print(arr * 2)
print(arr ** 2)
print(np.sqrt(arr))


[ 5  7  9 11 13 15]
[ 4  8 12 16 20 24]
[  4  16  36  64 100 144]
[1.41421356 2.         2.44948974 2.82842712 3.16227766 3.46410162]
