# Numpy (Numerical Python)

In [51]:
# Def:  Numpy is a open source python library for Numerical computations.

# Interview Question : What is the difference between python list  & numpy array?
# Ans: Ragvender: List are Heterogeneous, while numpy array are homogeneous.
# Numpy array are 50x faster than the list
# In Numpy array elements store in contineous memory location while in list
# (Accessing elements in contineous memory is faster)
# Numpy array are good at multiprocessors


# Numpy is designed C, C++, and Python


In [52]:
# Important Operations in Numpy

## 1. Installing, upgrading and importing numpy
## 2. Creating Numpy array's
## 3. Special type of numpy array creation
## 4. Array shape,  reshapping and transpose operations
## 5. Size, Datatype and their conversion
## 6. Indexing and Slicing and Modification
## 7. Mathematical and Stastistical operations
## 8. Concatination, Stacking, Splitting of numpy array's

## 1. Installing, upgrading and importing numpy

In [53]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [54]:
import numpy as np

In [55]:
np.__version__

'2.3.4'

## 2. Creating Numpy array's

In [56]:
# 1D array

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [57]:
arr = np.array([1,2,3,4,5.5])
print(arr)
print(type(arr))

[1.  2.  3.  4.  5.5]
<class 'numpy.ndarray'>


In [58]:
# datatype of elements
arr.dtype

dtype('float64')

In [59]:
arr = np.array([1,2,3,'Hello',5.5])
print(arr)
print(type(arr))
print(arr.dtype)

# U32 menas Unicode String data of max 32 length

['1' '2' '3' 'Hello' '5.5']
<class 'numpy.ndarray'>
<U32


In [60]:
# 2D numpy array

arr2 = np.array([['RRR','Bahuballi','OG'],['Ram Charan','Prabhas','Pawan Kalyan']])
arr2

array([['RRR', 'Bahuballi', 'OG'],
       ['Ram Charan', 'Prabhas', 'Pawan Kalyan']], dtype='<U12')

In [61]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
arr2.ndim

2

In [63]:
# 3D numpy Array

arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [64]:
arr3.ndim

3

In [65]:
arr3.shape

(2, 2, 3)

In [66]:
# 4D numpy array

arr4 = np.array([[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]])
arr4


array([[[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]],


       [[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]]])

In [67]:
arr4.ndim

4

In [68]:
arr4.shape

(2, 2, 2, 3)

## 3. Special type of numpy array creation

In [69]:
# Array of zeros

# 1D Zero numpy array 
zero_arr = np.zeros(5)
zero_arr

array([0., 0., 0., 0., 0.])

In [70]:
# 2D Zero numpy array 
zero_arr2 = np.zeros((3,3))
zero_arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
# 3D Zero numpy array 
zero_arr3 = np.zeros((2,2,3))
zero_arr3

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [72]:
# Create and Initialize the numpy array with 1 (one)

# 1D Ones numpy array 
one_arr = np.ones(5)
one_arr 

array([1., 1., 1., 1., 1.])

In [73]:
# 2D Ones numpy array 
one_arr2 = np.ones((2,3))
one_arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [74]:
# 3D Ones numpy array 
one_arr3 = np.ones((3,2,3))
one_arr3

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [75]:
# filling/initialize the numpy array with specific value

# 1D array with specific value
spe_arr = np.full(5, 20000)
spe_arr

array([20000, 20000, 20000, 20000, 20000])

In [76]:
# 2D array with specific value
spe_arr2 = np.full((3,2), 200)
spe_arr2

array([[200, 200],
       [200, 200],
       [200, 200]])

In [77]:
# 3D array with specific value
spe_arr3 = np.full((3,3,2), 20)
spe_arr3

array([[[20, 20],
        [20, 20],
        [20, 20]],

       [[20, 20],
        [20, 20],
        [20, 20]],

       [[20, 20],
        [20, 20],
        [20, 20]]])

In [78]:
# identity matrix

id = np.eye(4)
id

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
### random module in numpy

In [80]:
# 1D array of random elements
# rand() function generates uniformm distributrd values between 0 t0 1
np.random.rand(7)

array([7.78765841e-04, 9.92211559e-01, 6.17481510e-01, 6.11653160e-01,
       7.06630522e-03, 2.30624250e-02, 5.24774660e-01])

In [81]:
# 2D random array with values between 0 to 1 (uniformly distributed)

np.random.rand(2,3)


array([[0.39986097, 0.04666566, 0.97375552],
       [0.23277134, 0.09060643, 0.61838601]])

In [82]:
# 3D random array with values between 0 to 1 (uniformly distributed)

np.random.rand(2,2,3)

array([[[0.38246199, 0.98323089, 0.46676289],
        [0.85994041, 0.68030754, 0.45049925]],

       [[0.01326496, 0.94220176, 0.56328822],
        [0.3854165 , 0.01596625, 0.23089383]]])

In [83]:
# 4D random array with values between 0 to 1 (uniformly distributed)

np.random.rand(2,2,3,3)

array([[[[0.24102547, 0.68326352, 0.60999666],
         [0.83319491, 0.17336465, 0.39106061],
         [0.18223609, 0.75536141, 0.42515587]],

        [[0.20794166, 0.56770033, 0.03131329],
         [0.84228477, 0.44975413, 0.39515024],
         [0.92665887, 0.727272  , 0.32654077]]],


       [[[0.57044397, 0.52083426, 0.96117202],
         [0.84453385, 0.74732011, 0.53969213],
         [0.58675117, 0.96525531, 0.60703425]],

        [[0.27599918, 0.29627351, 0.16526694],
         [0.01563641, 0.42340148, 0.39488152],
         [0.29348817, 0.01407982, 0.1988424 ]]]])

In [84]:
# random()
np.random.random(5)

array([0.71134195, 0.79017554, 0.60595997, 0.92630088, 0.65107703])

In [85]:
np.random.random((2,3))


array([[0.91495968, 0.85003858, 0.44945067],
       [0.09541012, 0.37081825, 0.66884125]])

In [86]:
np.random.random((3,2,3))


array([[[0.66592236, 0.59129779, 0.27472179],
        [0.56124343, 0.38292687, 0.9717121 ]],

       [[0.84891382, 0.72172952, 0.23598492],
        [0.25606832, 0.04043359, 0.71066289]],

       [[0.11089082, 0.4393365 , 0.2017192 ],
        [0.8957636 , 0.47537022, 0.56327557]]])

In [87]:
# randn() : This will generate most of the random values betweeen -3 to +3
# randn() function generates values as standard normal distribution
# 1D array

np.random.randn(50)

array([-0.78204783,  0.42394307,  0.8727051 ,  2.28722598,  1.6229205 ,
        0.82373308,  0.29305925,  0.89663038, -0.61032202, -0.3161659 ,
       -1.48242425, -0.22884752,  0.96264129, -0.20969244, -0.77404293,
       -0.35977815,  0.72408325, -0.25576464,  0.8499212 , -1.31132423,
       -0.87030495, -0.50664322, -1.30995069,  2.94366342, -1.0962658 ,
        0.91488432, -0.66606062, -0.51378749,  0.3013228 , -1.45851692,
       -0.66273831, -0.14647281, -0.84601702, -0.82248937,  1.08672702,
        1.00498688, -0.44176602, -0.08416509,  1.23701607, -1.42647888,
        0.33802266,  1.9745712 ,  1.96503476, -1.93991122, -0.76262696,
        0.16865939, -1.32187695, -0.6682467 , -0.137291  ,  1.40132156])

In [88]:
np.random.randn(4,2)

array([[-0.04540266,  0.21693673],
       [ 0.51242373,  0.54348869],
       [ 0.02809946, -1.19708706],
       [ 0.7896728 ,  0.43148946]])

In [89]:
np.random.randn(2,3,2)

array([[[-1.0967523 , -0.68230156],
        [ 0.88751161,  0.60548313],
        [-0.72029799, -0.26993377]],

       [[-0.14346223,  0.61700378],
        [ 1.2489407 ,  0.06564916],
        [ 1.16920765,  0.87331697]]])

In [90]:
# randint() : generating integer values in a fix range

rand_int_data = np.random.randint(10, 100, 10) # 10 is inclusive, 100 is exclusive
rand_int_data


array([59, 32, 40, 51, 16, 25, 99, 69, 11, 10], dtype=int32)

In [91]:
rand_int_data = np.random.randint(10, 100, (3,4)) # 10 is inclusive, 100 is exclusive
rand_int_data

array([[57, 21, 78, 46],
       [41, 18, 28, 57],
       [89, 12, 29, 33]], dtype=int32)

In [92]:
rand_int_data = np.random.randint(10, 100, (3,4,3)) # 10 is inclusive, 100 is exclusive
rand_int_data


array([[[63, 42, 33],
        [84, 81, 45],
        [47, 93, 98],
        [34, 27, 91]],

       [[75, 63, 44],
        [89, 70, 50],
        [42, 77, 42],
        [23, 30, 57]],

       [[29, 17, 16],
        [76, 26, 42],
        [57, 85, 68],
        [95, 31, 39]]], dtype=int32)

In [93]:
# choice() : This is used  for selecting categorical data

GF = np.array(['Turky', 'Murgi', 'Chuhiya', 'Bakri'])

np.random.choice(GF, size = 2)

array(['Murgi', 'Murgi'], dtype='<U7')

In [94]:
np.random.choice(GF, size = 2, replace = False)

array(['Bakri', 'Murgi'], dtype='<U7')

In [95]:
np.random.choice(GF, size = 10, p = [0.4, 0.3, 0.2, 0.1])

array(['Bakri', 'Murgi', 'Turky', 'Murgi', 'Murgi', 'Chuhiya', 'Turky',
       'Murgi', 'Murgi', 'Chuhiya'], dtype='<U7')

In [96]:
np.random.seed(42)
np.random.choice(GF, size = 3)

array(['Chuhiya', 'Bakri', 'Turky'], dtype='<U7')

In [97]:
### Create sequences, shuffled, linearly, spaced array
arr1 = np.arange(1,10,1) # 1 is inclusive, 10 is exclusive
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
np.random.shuffle(arr1)
arr1

array([6, 1, 4, 7, 3, 2, 9, 5, 8])

In [99]:
# permutation don't modify the original array
arr2 = np.random.permutation(arr1)
arr2

array([6, 2, 9, 1, 8, 4, 7, 3, 5])

In [100]:
# Generate linear spaced numbers between 1 to 10
arr3 = np.linspace(1,10,5) # linespace(start, end, size)
arr3

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])